/* Generated by D:\OpenDDS\bin\opendds_idl version 3.12 (ACE version 6.2a_p14) running on input file Datatransfer.idl */
#include "DatatransferTypeSupportImpl.h"

#include <cstring>
#include <stdexcept>
#include "dds/DCPS/BuiltInTopicUtils.h"
#include "dds/DCPS/ContentFilteredTopicImpl.h"
#include "dds/DCPS/DataReaderImpl_T.h"
#include "dds/DCPS/DataWriterImpl_T.h"
#include "dds/DCPS/FilterEvaluator.h"
#include "dds/DCPS/MultiTopicDataReader_T.h"
#include "dds/DCPS/PoolAllocator.h"
#include "dds/DCPS/PublicationInstance.h"
#include "dds/DCPS/PublisherImpl.h"
#include "dds/DCPS/Qos_Helper.h"
#include "dds/DCPS/RakeData.h"
#include "dds/DCPS/RakeResults_T.h"
#include "dds/DCPS/ReceivedDataElementList.h"
#include "dds/DCPS/Registered_Data_Types.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/SubscriberImpl.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/debug.h"
#include "dds/DdsDcpsDomainC.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Datatransfer */



/* Begin STRUCT: Variables */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const Datatransfer::Variables& stru, size_t& size, size_t& padding)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(padding);
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.var_id);
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.entity.in()) + 1;
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.count);
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.vars.in()) + 1;
  find_size_ulong(size, padding);
  size += ACE_OS::strlen(stru.type.in()) + 1;
}

bool operator<<(Serializer& strm, const Datatransfer::Variables& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm << stru.var_id)
    && (strm << stru.entity.in())
    && (strm << stru.count)
    && (strm << stru.vars.in())
    && (strm << stru.type.in());
}

bool operator>>(Serializer& strm, Datatransfer::Variables& stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm >> stru.var_id)
    && (strm >> stru.entity.out())
    && (strm >> stru.count)
    && (strm >> stru.vars.out())
    && (strm >> stru.type.out());
}

size_t gen_max_marshaled_size(const Datatransfer::Variables& stru, bool align)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(align);
  return 0;
}

size_t gen_max_marshaled_size(KeyOnly<const Datatransfer::Variables> stru, bool align)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(align);
  return 4;
}

void gen_find_size(KeyOnly<const Datatransfer::Variables> stru, size_t& size, size_t& padding)
{
  ACE_UNUSED_ARG(stru);
  ACE_UNUSED_ARG(size);
  ACE_UNUSED_ARG(padding);
  if ((size + padding) % 4) {
    padding += 4 - ((size + padding) % 4);
  }
  size += gen_max_marshaled_size(stru.t.var_id);
}

bool operator<<(Serializer& strm, KeyOnly<const Datatransfer::Variables> stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm << stru.t.var_id);
}

bool operator>>(Serializer& strm, KeyOnly<Datatransfer::Variables> stru)
{
  ACE_UNUSED_ARG(strm);
  ACE_UNUSED_ARG(stru);
  return (strm >> stru.t.var_id);
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Datatransfer {
::DDS::DataWriter_ptr VariablesTypeSupportImpl::create_datawriter()
{
  typedef OpenDDS::DCPS::DataWriterImpl_T<Variables> DataWriterImplType;
  ::DDS::DataWriter_ptr writer_impl = ::DDS::DataWriter::_nil();
  ACE_NEW_NORETURN(writer_impl,
                   DataWriterImplType());
  return writer_impl;
}
::DDS::DataReader_ptr VariablesTypeSupportImpl::create_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Variables> DataReaderImplType;
  ::DDS::DataReader_ptr reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(reader_impl,
                   DataReaderImplType());
  return reader_impl;
}
#ifndef OPENDDS_NO_MULTI_TOPIC
::DDS::DataReader_ptr VariablesTypeSupportImpl::create_multitopic_datareader()
{
  typedef OpenDDS::DCPS::DataReaderImpl_T<Variables> DataReaderImplType;
  typedef OpenDDS::DCPS::MultiTopicDataReader_T<Variables, DataReaderImplType> MultiTopicDataReaderImplType;
  ::DDS::DataReader_ptr multitopic_reader_impl = ::DDS::DataReader::_nil();
  ACE_NEW_NORETURN(multitopic_reader_impl,
                   MultiTopicDataReaderImplType());
  return multitopic_reader_impl;
}
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
const OpenDDS::DCPS::MetaStruct& VariablesTypeSupportImpl::getMetaStructForType()
{
  return OpenDDS::DCPS::getMetaStruct<Variables>();
}
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
bool VariablesTypeSupportImpl::has_dcps_key()
{
  return TraitsType::gen_has_key ();
}
const char* VariablesTypeSupportImpl::default_type_name() const
{
  return TraitsType::type_name();
}
VariablesTypeSupport::_ptr_type VariablesTypeSupportImpl::_narrow(CORBA::Object_ptr obj)
{
  return TypeSupportType::_narrow(obj);
}
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<>
struct MetaStructImpl<Datatransfer::Variables> : MetaStruct {
  typedef Datatransfer::Variables T;

#ifndef OPENDDS_NO_MULTI_TOPIC
  void* allocate() const { return new T; }

  void deallocate(void* stru) const { delete static_cast<T*>(stru); }
  size_t numDcpsKeys() const { return 1; }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  Value getValue(const void* stru, const char* field) const
  {
    const Datatransfer::Variables& typed = *static_cast<const Datatransfer::Variables*>(stru);
    if (std::strcmp(field, "var_id") == 0) {
      return typed.var_id;
    }
    if (std::strcmp(field, "entity") == 0) {
      return typed.entity.in();
    }
    if (std::strcmp(field, "count") == 0) {
      return typed.count;
    }
    if (std::strcmp(field, "vars") == 0) {
      return typed.vars.in();
    }
    if (std::strcmp(field, "type") == 0) {
      return typed.type.in();
    }
    ACE_UNUSED_ARG(typed);
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct Datatransfer::Variables)");
  }

  Value getValue(Serializer& ser, const char* field) const
  {
    if (std::strcmp(field, "var_id") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'var_id' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'var_id' could not be skipped");
      }
    }
    if (std::strcmp(field, "entity") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'entity' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'entity' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'entity' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "count") == 0) {
      ACE_CDR::Long val;
      if (!(ser >> val)) {
        throw std::runtime_error("Field 'count' could not be deserialized");
      }
      return val;
    } else {
      if (!ser.skip(1, 4)) {
        throw std::runtime_error("Field 'count' could not be skipped");
      }
    }
    if (std::strcmp(field, "vars") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'vars' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'vars' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'vars' contents could not be skipped");
      }
    }
    if (std::strcmp(field, "type") == 0) {
      TAO::String_Manager val;
      if (!(ser >> val.out())) {
        throw std::runtime_error("Field 'type' could not be deserialized");
      }
      return val;
    } else {
      ACE_CDR::ULong len;
      if (!(ser >> len)) {
        throw std::runtime_error("String 'type' length could not be deserialized");
      }
      if (!ser.skip(len)) {
        throw std::runtime_error("String 'type' contents could not be skipped");
      }
    }
    if (!field[0]) {
      return 0;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not valid for struct Datatransfer::Variables");
  }

  ComparatorBase::Ptr create_qc_comparator(const char* field, ComparatorBase::Ptr next) const
  {
    ACE_UNUSED_ARG(next);
    if (std::strcmp(field, "var_id") == 0) {
      return make_field_cmp(&T::var_id, next);
    }
    if (std::strcmp(field, "entity") == 0) {
      return make_field_cmp(&T::entity, next);
    }
    if (std::strcmp(field, "count") == 0) {
      return make_field_cmp(&T::count, next);
    }
    if (std::strcmp(field, "vars") == 0) {
      return make_field_cmp(&T::vars, next);
    }
    if (std::strcmp(field, "type") == 0) {
      return make_field_cmp(&T::type, next);
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct Datatransfer::Variables)");
  }

#ifndef OPENDDS_NO_MULTI_TOPIC
  const char** getFieldNames() const
  {
    static const char* names[] = {"var_id", "entity", "count", "vars", "type", 0};
    return names;
  }

  const void* getRawField(const void* stru, const char* field) const
  {
    if (std::strcmp(field, "var_id") == 0) {
      return &static_cast<const T*>(stru)->var_id;
    }
    if (std::strcmp(field, "entity") == 0) {
      return &static_cast<const T*>(stru)->entity;
    }
    if (std::strcmp(field, "count") == 0) {
      return &static_cast<const T*>(stru)->count;
    }
    if (std::strcmp(field, "vars") == 0) {
      return &static_cast<const T*>(stru)->vars;
    }
    if (std::strcmp(field, "type") == 0) {
      return &static_cast<const T*>(stru)->type;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct Datatransfer::Variables)");
  }

  void assign(void* lhs, const char* field, const void* rhs,
    const char* rhsFieldSpec, const MetaStruct& rhsMeta) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    ACE_UNUSED_ARG(rhsFieldSpec);
    ACE_UNUSED_ARG(rhsMeta);
    if (std::strcmp(field, "var_id") == 0) {
      static_cast<T*>(lhs)->var_id = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "entity") == 0) {
      static_cast<T*>(lhs)->entity = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "count") == 0) {
      static_cast<T*>(lhs)->count = *static_cast<const CORBA::Long*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "vars") == 0) {
      static_cast<T*>(lhs)->vars = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    if (std::strcmp(field, "type") == 0) {
      static_cast<T*>(lhs)->type = *static_cast<const TAO::String_Manager*>(rhsMeta.getRawField(rhs, rhsFieldSpec));
      return;
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct Datatransfer::Variables)");
  }
#endif /* OPENDDS_NO_MULTI_TOPIC */

  bool compare(const void* lhs, const void* rhs, const char* field) const
  {
    ACE_UNUSED_ARG(lhs);
    ACE_UNUSED_ARG(field);
    ACE_UNUSED_ARG(rhs);
    if (std::strcmp(field, "var_id") == 0) {
      return static_cast<const T*>(lhs)->var_id == static_cast<const T*>(rhs)->var_id;
    }
    if (std::strcmp(field, "entity") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->entity.in(), static_cast<const T*>(rhs)->entity.in());
    }
    if (std::strcmp(field, "count") == 0) {
      return static_cast<const T*>(lhs)->count == static_cast<const T*>(rhs)->count;
    }
    if (std::strcmp(field, "vars") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->vars.in(), static_cast<const T*>(rhs)->vars.in());
    }
    if (std::strcmp(field, "type") == 0) {
      return 0 == ACE_OS::strcmp(static_cast<const T*>(lhs)->type.in(), static_cast<const T*>(rhs)->type.in());
    }
    throw std::runtime_error("Field " + OPENDDS_STRING(field) + " not found or its type is not supported (in struct Datatransfer::Variables)");
  }
};

template<>
const MetaStruct& getMetaStruct<Datatransfer::Variables>()
{
  static MetaStructImpl<Datatransfer::Variables> msi;
  return msi;
}

bool gen_skip_over(Serializer& ser, Datatransfer::Variables*)
{
  ACE_UNUSED_ARG(ser);
  MetaStructImpl<Datatransfer::Variables>().getValue(ser, "");
  return true;
}

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: Variables */

/* End MODULE: Datatransfer */
