// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be\be_codegen.cpp:376


#include "DatatransferTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DatatransferTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Datatransfer::VariablesTypeSupport.

Datatransfer::VariablesTypeSupport_ptr
TAO::Objref_Traits<Datatransfer::VariablesTypeSupport>::duplicate (
    Datatransfer::VariablesTypeSupport_ptr p)
{
  return Datatransfer::VariablesTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Datatransfer::VariablesTypeSupport>::release (
    Datatransfer::VariablesTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Datatransfer::VariablesTypeSupport_ptr
TAO::Objref_Traits<Datatransfer::VariablesTypeSupport>::nil (void)
{
  return Datatransfer::VariablesTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Datatransfer::VariablesTypeSupport>::marshal (
    const Datatransfer::VariablesTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Datatransfer::VariablesTypeSupport::VariablesTypeSupport (void)
{}

Datatransfer::VariablesTypeSupport::~VariablesTypeSupport (void)
{
}

Datatransfer::VariablesTypeSupport_ptr
Datatransfer::VariablesTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesTypeSupport::_duplicate (
      dynamic_cast<VariablesTypeSupport_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesTypeSupport_ptr
Datatransfer::VariablesTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesTypeSupport::_duplicate (
      dynamic_cast<VariablesTypeSupport_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesTypeSupport_ptr
Datatransfer::VariablesTypeSupport::_nil (void)
{
  return 0;
}

Datatransfer::VariablesTypeSupport_ptr
Datatransfer::VariablesTypeSupport::_duplicate (VariablesTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Datatransfer::VariablesTypeSupport::_tao_release (VariablesTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Datatransfer::VariablesTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Datatransfer/VariablesTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Datatransfer::VariablesTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Datatransfer/VariablesTypeSupport:1.0";
}

::CORBA::Boolean
Datatransfer::VariablesTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Datatransfer::VariablesDataWriter.

Datatransfer::VariablesDataWriter_ptr
TAO::Objref_Traits<Datatransfer::VariablesDataWriter>::duplicate (
    Datatransfer::VariablesDataWriter_ptr p)
{
  return Datatransfer::VariablesDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Datatransfer::VariablesDataWriter>::release (
    Datatransfer::VariablesDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Datatransfer::VariablesDataWriter_ptr
TAO::Objref_Traits<Datatransfer::VariablesDataWriter>::nil (void)
{
  return Datatransfer::VariablesDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Datatransfer::VariablesDataWriter>::marshal (
    const Datatransfer::VariablesDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Datatransfer::VariablesDataWriter::VariablesDataWriter (void)
{}

Datatransfer::VariablesDataWriter::~VariablesDataWriter (void)
{
}

Datatransfer::VariablesDataWriter_ptr
Datatransfer::VariablesDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesDataWriter::_duplicate (
      dynamic_cast<VariablesDataWriter_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesDataWriter_ptr
Datatransfer::VariablesDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesDataWriter::_duplicate (
      dynamic_cast<VariablesDataWriter_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesDataWriter_ptr
Datatransfer::VariablesDataWriter::_nil (void)
{
  return 0;
}

Datatransfer::VariablesDataWriter_ptr
Datatransfer::VariablesDataWriter::_duplicate (VariablesDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Datatransfer::VariablesDataWriter::_tao_release (VariablesDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Datatransfer::VariablesDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Datatransfer/VariablesDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Datatransfer::VariablesDataWriter::_interface_repository_id (void) const
{
  return "IDL:Datatransfer/VariablesDataWriter:1.0";
}

::CORBA::Boolean
Datatransfer::VariablesDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Datatransfer::VariablesDataReader.

Datatransfer::VariablesDataReader_ptr
TAO::Objref_Traits<Datatransfer::VariablesDataReader>::duplicate (
    Datatransfer::VariablesDataReader_ptr p)
{
  return Datatransfer::VariablesDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Datatransfer::VariablesDataReader>::release (
    Datatransfer::VariablesDataReader_ptr p)
{
  ::CORBA::release (p);
}

Datatransfer::VariablesDataReader_ptr
TAO::Objref_Traits<Datatransfer::VariablesDataReader>::nil (void)
{
  return Datatransfer::VariablesDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Datatransfer::VariablesDataReader>::marshal (
    const Datatransfer::VariablesDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Datatransfer::VariablesDataReader::VariablesDataReader (void)
{}

Datatransfer::VariablesDataReader::~VariablesDataReader (void)
{
}

Datatransfer::VariablesDataReader_ptr
Datatransfer::VariablesDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesDataReader::_duplicate (
      dynamic_cast<VariablesDataReader_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesDataReader_ptr
Datatransfer::VariablesDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return VariablesDataReader::_duplicate (
      dynamic_cast<VariablesDataReader_ptr> (_tao_objref)
    );
}

Datatransfer::VariablesDataReader_ptr
Datatransfer::VariablesDataReader::_nil (void)
{
  return 0;
}

Datatransfer::VariablesDataReader_ptr
Datatransfer::VariablesDataReader::_duplicate (VariablesDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Datatransfer::VariablesDataReader::_tao_release (VariablesDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Datatransfer::VariablesDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Datatransfer/VariablesDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Datatransfer::VariablesDataReader::_interface_repository_id (void) const
{
  return "IDL:Datatransfer/VariablesDataReader:1.0";
}

::CORBA::Boolean
Datatransfer::VariablesDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

