// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p14
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:152

#ifndef _TAO_IDL_DATATRANSFERTYPESUPPORTC_IHN5OL_H_
#define _TAO_IDL_DATATRANSFERTYPESUPPORTC_IHN5OL_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DatatransferC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:38

namespace Datatransfer
{

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Datatransfer::Variables, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> VariablesSeq;
  

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATATRANSFER_VARIABLESTYPESUPPORT__VAR_OUT_CH_)
#define _DATATRANSFER_VARIABLESTYPESUPPORT__VAR_OUT_CH_

  class VariablesTypeSupport;
  typedef VariablesTypeSupport *VariablesTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        VariablesTypeSupport
      >
    VariablesTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        VariablesTypeSupport
      >
    VariablesTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  VariablesTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef VariablesTypeSupport_ptr _ptr_type;
    typedef VariablesTypeSupport_var _var_type;
    typedef VariablesTypeSupport_out _out_type;

    // The static operations.
    static VariablesTypeSupport_ptr _duplicate (VariablesTypeSupport_ptr obj);

    static void _tao_release (VariablesTypeSupport_ptr obj);

    static VariablesTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static VariablesTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static VariablesTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    VariablesTypeSupport (void);

    

    virtual ~VariablesTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    VariablesTypeSupport (const VariablesTypeSupport &);

    void operator= (const VariablesTypeSupport &);
  };

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATATRANSFER_VARIABLESDATAWRITER__VAR_OUT_CH_)
#define _DATATRANSFER_VARIABLESDATAWRITER__VAR_OUT_CH_

  class VariablesDataWriter;
  typedef VariablesDataWriter *VariablesDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        VariablesDataWriter
      >
    VariablesDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        VariablesDataWriter
      >
    VariablesDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  VariablesDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef VariablesDataWriter_ptr _ptr_type;
    typedef VariablesDataWriter_var _var_type;
    typedef VariablesDataWriter_out _out_type;

    // The static operations.
    static VariablesDataWriter_ptr _duplicate (VariablesDataWriter_ptr obj);

    static void _tao_release (VariablesDataWriter_ptr obj);

    static VariablesDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static VariablesDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static VariablesDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Datatransfer::Variables & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Datatransfer::Variables & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Datatransfer::Variables & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Datatransfer::Variables & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Datatransfer::Variables & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Datatransfer::Variables & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Datatransfer::Variables & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Datatransfer::Variables & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Datatransfer::Variables & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Datatransfer::Variables & instance_data) = 0;

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    VariablesDataWriter (void);

    

    virtual ~VariablesDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    VariablesDataWriter (const VariablesDataWriter &);

    void operator= (const VariablesDataWriter &);
  };

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:751

#if !defined (_DATATRANSFER_VARIABLESDATAREADER__VAR_OUT_CH_)
#define _DATATRANSFER_VARIABLESDATAREADER__VAR_OUT_CH_

  class VariablesDataReader;
  typedef VariablesDataReader *VariablesDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        VariablesDataReader
      >
    VariablesDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        VariablesDataReader
      >
    VariablesDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:43

  class  VariablesDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:307

    typedef VariablesDataReader_ptr _ptr_type;
    typedef VariablesDataReader_var _var_type;
    typedef VariablesDataReader_out _out_type;

    // The static operations.
    static VariablesDataReader_ptr _duplicate (VariablesDataReader_ptr obj);

    static void _tao_release (VariablesDataReader_ptr obj);

    static VariablesDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static VariablesDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static VariablesDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Datatransfer::VariablesSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Datatransfer::VariablesSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Datatransfer::Variables & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Datatransfer::Variables & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Datatransfer::VariablesSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Datatransfer::VariablesSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Datatransfer::VariablesSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Datatransfer::Variables & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Datatransfer::Variables & instance_data) = 0;

    // TAO_IDL - Generated from
    // s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    VariablesDataReader (void);

    

    virtual ~VariablesDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    VariablesDataReader (const VariablesDataReader &);

    void operator= (const VariablesDataReader &);
  };

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:67

} // module Datatransfer

// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DATATRANSFER_VARIABLESTYPESUPPORT__TRAITS_)
#define _DATATRANSFER_VARIABLESTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Datatransfer::VariablesTypeSupport>
  {
    static ::Datatransfer::VariablesTypeSupport_ptr duplicate (
        ::Datatransfer::VariablesTypeSupport_ptr p);
    static void release (
        ::Datatransfer::VariablesTypeSupport_ptr p);
    static ::Datatransfer::VariablesTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Datatransfer::VariablesTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATATRANSFER_VARIABLESDATAWRITER__TRAITS_)
#define _DATATRANSFER_VARIABLESDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Datatransfer::VariablesDataWriter>
  {
    static ::Datatransfer::VariablesDataWriter_ptr duplicate (
        ::Datatransfer::VariablesDataWriter_ptr p);
    static void release (
        ::Datatransfer::VariablesDataWriter_ptr p);
    static ::Datatransfer::VariablesDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Datatransfer::VariablesDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DATATRANSFER_VARIABLESDATAREADER__TRAITS_)
#define _DATATRANSFER_VARIABLESDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Datatransfer::VariablesDataReader>
  {
    static ::Datatransfer::VariablesDataReader_ptr duplicate (
        ::Datatransfer::VariablesDataReader_ptr p);
    static void release (
        ::Datatransfer::VariablesDataReader_ptr p);
    static ::Datatransfer::VariablesDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Datatransfer::VariablesDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// s:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "DatatransferTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

