/* -*- C++ -*- */
/* Generated by S:\OpenDDS\bin\opendds_idl version 3.12 (ACE version 6.2a_p14) running on input file Datatransfer.idl */
#ifndef OPENDDS_IDL_GENERATED_DATATRANSFERTYPESUPPORTIMPL_H_FEU5PN
#define OPENDDS_IDL_GENERATED_DATATRANSFERTYPESUPPORTIMPL_H_FEU5PN
#include "DatatransferC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "DatatransferTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Datatransfer */



/* Begin STRUCT: Variables */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const Datatransfer::Variables& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Datatransfer::Variables& stru);

bool operator>>(Serializer& strm, Datatransfer::Variables& stru);

size_t gen_max_marshaled_size(const Datatransfer::Variables& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const Datatransfer::Variables> stru, bool align);

void gen_find_size(KeyOnly<const Datatransfer::Variables> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const Datatransfer::Variables> stru);

bool operator>>(Serializer& strm, KeyOnly<Datatransfer::Variables> stru);

template <>
struct MarshalTraits<Datatransfer::Variables> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Datatransfer {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  Variables_OpenDDS_KeyLessThan {
  bool operator()(const Datatransfer::Variables& v1, const Datatransfer::Variables& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.var_id < v2.var_id) return true;
    if (v2.var_id < v1.var_id) return false;
    return false;
  }
};
}


namespace Datatransfer {
class VariablesTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<Datatransfer::Variables> {
  typedef Datatransfer::Variables MessageType;
  typedef Datatransfer::VariablesSeq MessageSequenceType;
  typedef Datatransfer::VariablesTypeSupport TypeSupportType;
  typedef Datatransfer::VariablesTypeSupportImpl TypeSupportTypeImpl;
  typedef Datatransfer::VariablesDataWriter DataWriterType;
  typedef Datatransfer::VariablesDataReader DataReaderType;
  typedef Datatransfer::Variables_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "Datatransfer::Variables"; }
  static bool gen_has_key () { return true; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Datatransfer {
class  VariablesTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<VariablesTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<Variables> TraitsType;
  typedef VariablesTypeSupport TypeSupportType;
  typedef VariablesTypeSupport::_var_type _var_type;
  typedef VariablesTypeSupport::_ptr_type _ptr_type;

  VariablesTypeSupportImpl() {}
  virtual ~VariablesTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static VariablesTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Datatransfer::Variables>();
bool gen_skip_over(Serializer& ser, Datatransfer::Variables*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: Variables */

/* End MODULE: Datatransfer */
#endif /* OPENDDS_IDL_GENERATED_DATATRANSFERTYPESUPPORTIMPL_H_FEU5PN */
